[build]
  publish = "dist/"
  command = "cp src/style.css dist/ && cp -r src/assets dist/ && yarn elm make src/Main.elm --output=dist/index.html"

[build.environment]
  ELM_HOME = "$NETLIFY_BUILD_BASE/cache/elm"